Nav changes and styling changes for subheadings in discover section
18F/product-guide pull request #145
Opened 2020-12-16 21:44 UTC by allisonnorman

- Changed stakeholder file name from "process" to "stakeholders"
- Updated navigation titles for discover section
- Updated md styling from bold to ## for each subheading in the discover section

2020-12-17 20:36 UTC, colinmurphy01 commented on _data/navigation.yml
>          href: /discover/audience/
consider updating
```suggestion
        href: /discover/users/
```

2020-12-17 20:36 UTC, colinmurphy01 commented on discover/audience.md
> +## RESOURCES
```suggestion
## Resources
```

2020-12-17 20:36 UTC, colinmurphy01 commented on discover/stakeholders.md
> +## RESOURCES
```suggestion
## Resources
```

2020-12-17 20:37 UTC, colinmurphy01 commented on discover/technical.md
> +## RESOURCES
```suggestion
## Resources
```

2020-12-17 20:40 UTC, colinmurphy01 requested changes
Added some comments and suggestions.

I couldn't do this within the review UI, but additionally can you update the page titles to sentence case.

2020-12-18 17:57 UTC, allisonnorman commented
@colinmurphy01 Thanks! I made your changes and also updated the file name for /users to reflect your url path naming suggestion.

2020-12-18 18:43 UTC, colinmurphy01 approved these changes

2020-12-18 20:58 UTC, merged